CREATE TABLE users(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100),email VARCHAR(100),password VARCHAR(255),wallet_balance DECIMAL(10,2) DEFAULT 0);
CREATE TABLE transactions(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT,type VARCHAR(10),amount DECIMAL(10,2),note VARCHAR(255),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE operators(id INT AUTO_INCREMENT PRIMARY KEY,code VARCHAR(10),name VARCHAR(100));
CREATE TABLE recharges(id INT AUTO_INCREMENT PRIMARY KEY,user_id INT,operator_code VARCHAR(10),number VARCHAR(20),amount DECIMAL(10,2),status VARCHAR(50),txid VARCHAR(100),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
